<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ying Hui Tan">
<meta name="dcterms.date" content="2026-06-01">
<meta name="description" content="Using an Analysis of Variance (ANOVA) and linear contrasts in R to determine the optimal combination of cup material, lids, and stirring for heat dispersal.">

<title>A 3x2x2 Factorial Design on Coffee Cooling – Confounding Human</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e647879dc0e26262fb7d9aca73064a4a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Confounding Human</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/yingghui23"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/tan-ying-hui23/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3ByB3dxP8gQESEyO24EnDJ%2BA%3D%3D"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">A 3x2x2 Factorial Design on Coffee Cooling</h1>
                  <div>
        <div class="description">
          Using an Analysis of Variance (ANOVA) and linear contrasts in R to determine the optimal combination of cup material, lids, and stirring for heat dispersal.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">DOE</div>
                <div class="quarto-category">R</div>
                <div class="quarto-category">BIBD</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ying Hui Tan </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">June 1, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="overview-the-core-objective" class="level2">
<h2 class="anchored" data-anchor-id="overview-the-core-objective">Overview: The Core Objective</h2>
<p>While it seems like common sense on which factors affect coffee cooling in general, I guess the main point of this blog is to understand the key concepts of Design of Experiment (DoE). Elements like linear contrast and factorial design could be applied to real world data in manufacturing plants or product analytics.</p>
<hr>
</section>
<section id="the-problem-what-cools-coffee-fastest" class="level2">
<h2 class="anchored" data-anchor-id="the-problem-what-cools-coffee-fastest">The Problem: What Cools Coffee Fastest?</h2>
<p>Ever wondered what is the optimal way to cool down hot coffee? In this project, we experiment with different methods of cooling a cup of coffee by varying three factors: the material of the cup, stirring, and the addition of a lid. The goal is to determine the most effective combination for cooling coffee under controlled environmental conditions.</p>
<p>The primary response variable is the <strong>temperature of the coffee after a fixed time interval (10 minutes)</strong>.</p>
<hr>
</section>
<section id="experimental-setup-controls" class="level2">
<h2 class="anchored" data-anchor-id="experimental-setup-controls">Experimental Setup &amp; Controls</h2>
<p>To ensure consistency and isolate the true treatment effects, several critical engineering controls were implemented: * <strong>Fixed Environment:</strong> All trials were conducted in a single room with the thermostat locked at <strong>80°F</strong>. * <strong>Standardized Initial State:</strong> Water was heated in the same vessel to a full boil, poured immediately, and standardized to an initial temperature of <strong>180°F</strong>. * <strong>Standardized Stirring:</strong> The stirring protocol was strictly controlled at <strong>1 rotation per second for exactly 1 minute</strong>. * <strong>System Cleanliness:</strong> Cups were thoroughly washed and allowed to rest for 15 minutes before reuse to return to room temperature.</p>
<section id="factors-of-interest-3x2x2-factorial-design" class="level3">
<h3 class="anchored" data-anchor-id="factors-of-interest-3x2x2-factorial-design">Factors of Interest (3x2x2 Factorial Design)</h3>
<p>We evaluated 12 distinct treatment combinations with <strong>2 replications per treatment</strong>, resulting in a total of 24 experimental units (individual cups of coffee).</p>
<ul>
<li><strong>Cup Material (3 Levels):</strong> Ceramic, Paper, Insulated Metal</li>
<li><strong>Lid (2 Levels):</strong> Lid (+) vs.&nbsp;No Lid (-)</li>
<li><strong>Stirring (2 Levels):</strong> Stir (+) vs.&nbsp;No Stir (-)</li>
</ul>
<p>In addition to the factorial design, there is a blocking effect (Morning vs Afternoon), in consideration of the time frame the experiement is conducted. Hence, this is a 3x2x2 Full Factorial Design arranged in Randomised Complete Block Design (RCBD).</p>
<p>The statistical linear model for this 3x2x2 randomized blocked factorial design is expressed as:</p>
<p><span class="math display">\[Y_{ijkl} = \mu + \gamma_i + \alpha_j + \beta_k + \delta_l + (\alpha\beta)_{jk} + (\alpha\delta)_{jl} + (\beta\delta)_{kl} + (\alpha\beta\delta)_{jkl} + \epsilon_{ijkl}\]</span></p>
<p>Definition of Terms: * <span class="math inline">\(Y_{ijkl}\)</span>: The observed final coffee temperature for the <span class="math inline">\(i\)</span>-th block, <span class="math inline">\(j\)</span>-th cup material, <span class="math inline">\(k\)</span>-th lid status, and <span class="math inline">\(l\)</span>-th stirring status.</p>
<ul>
<li><p><span class="math inline">\(\mu\)</span>: The overall grand mean of the coffee temperature.<span class="math inline">\(\gamma_i\)</span>: The effect of the <span class="math inline">\(i\)</span>-th Block (Morning vs.&nbsp;Afternoon), where <span class="math inline">\(i = 1, 2\)</span>.</p></li>
<li><p><span class="math inline">\(\alpha_j\)</span>: The main effect of the <span class="math inline">\(j\)</span>-th factor, Cup Material (Ceramic, Paper, Insulated Metal), where <span class="math inline">\(j = 1, 2, 3\)</span>.</p></li>
<li><p><span class="math inline">\(\beta_k\)</span>: The main effect of the <span class="math inline">\(k\)</span>-th factor, Lid (Yes vs.&nbsp;No), where <span class="math inline">\(k = 1, 2\)</span>.</p></li>
<li><p><span class="math inline">\(\delta_l\)</span>: The main effect of the <span class="math inline">\(l\)</span>-th factor, Stirring (Yes vs.&nbsp;No), where <span class="math inline">\(l = 1, 2\)</span>.</p></li>
<li><p><span class="math inline">\((\alpha\beta)_{jk}\)</span>: The 2-way interaction effect between Cup Material and Lid. (Significant in your data!)</p></li>
<li><p><span class="math inline">\((\alpha\delta)_{jl}\)</span>: The 2-way interaction effect between Cup Material and Stirring.</p></li>
<li><p><span class="math inline">\((\beta\delta)_{kl}\)</span>: The 2-way interaction effect between Lid and Stirring.</p></li>
<li><p><span class="math inline">\((\alpha\beta\delta)_{jkl}\)</span>: The 3-way interaction effect between Cup Material, Lid, and Stirring.</p></li>
<li><p><span class="math inline">\(\epsilon_{ijkl}\)</span>: The random experimental error term, assumed to be independent and identically distributed (i.i.d.) following a normal distribution: <span class="math inline">\(\epsilon_{ijkl} \sim N(0, \sigma^2)\)</span>.</p></li>
</ul>
<hr>
</section>
</section>
<section id="data-loading-the-raw-numbers" class="level2">
<h2 class="anchored" data-anchor-id="data-loading-the-raw-numbers">Data Loading &amp; The Raw Numbers</h2>
<p>To analyze this properly, I loaded the 24 experimental runs into R. I also accounted for a <strong>Blocking Factor</strong> (Morning vs.&nbsp;Afternoon runs) just in case the ambient temperature outside leaked into the room and messed with our data.</p>
<p>Here is what the raw dataset looks like:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating our 3x2x2 factorial dataset</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>coffee_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">treatment =</span> <span class="fu">rep</span>(<span class="fu">paste0</span>(<span class="st">"T"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>), <span class="at">each =</span> <span class="dv">2</span>),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">material =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"ceramic"</span>,<span class="st">"ceramic"</span>,<span class="st">"ceramic"</span>,<span class="st">"ceramic"</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"paper"</span>,<span class="st">"paper"</span>,<span class="st">"paper"</span>,<span class="st">"paper"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"metal"</span>,<span class="st">"metal"</span>,<span class="st">"metal"</span>,<span class="st">"metal"</span>), <span class="at">each =</span> <span class="dv">2</span>),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">lid =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"yes"</span>,<span class="st">"yes"</span>,<span class="st">"no"</span>,<span class="st">"no"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>              <span class="st">"no"</span>,<span class="st">"no"</span>,<span class="st">"yes"</span>,<span class="st">"yes"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>              <span class="st">"yes"</span>,<span class="st">"yes"</span>,<span class="st">"no"</span>,<span class="st">"no"</span>), <span class="at">each =</span> <span class="dv">2</span>),</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">stir =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"yes"</span>,<span class="st">"no"</span>,<span class="st">"no"</span>,<span class="st">"yes"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>               <span class="st">"no"</span>,<span class="st">"yes"</span>,<span class="st">"no"</span>,<span class="st">"yes"</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>               <span class="st">"yes"</span>,<span class="st">"no"</span>,<span class="st">"no"</span>,<span class="st">"yes"</span>), <span class="at">each =</span> <span class="dv">2</span>),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">block =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Morning"</span>, <span class="st">"Afternoon"</span>), <span class="at">times =</span> <span class="dv">12</span>),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">temp =</span> <span class="fu">c</span>(</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="dv">138</span>,<span class="dv">152</span>,<span class="dv">150</span>,<span class="dv">150</span>,<span class="dv">126</span>,<span class="dv">134</span>,<span class="dv">126</span>,<span class="dv">136</span>,<span class="dv">146</span>,<span class="dv">150</span>,<span class="dv">144</span>,<span class="dv">143</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="dv">150</span>,<span class="dv">154</span>,<span class="dv">152</span>,<span class="dv">149</span>,<span class="dv">162</span>,<span class="dv">165</span>,<span class="dv">168</span>,<span class="dv">169</span>,<span class="dv">158</span>,<span class="dv">158</span>,<span class="dv">161</span>,<span class="dv">160</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Converting characters to factors for ANOVA</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>coffee_df<span class="sc">$</span>material <span class="ot">&lt;-</span> <span class="fu">factor</span>(coffee_df<span class="sc">$</span>material)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>coffee_df<span class="sc">$</span>lid <span class="ot">&lt;-</span> <span class="fu">factor</span>(coffee_df<span class="sc">$</span>lid)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>coffee_df<span class="sc">$</span>stir <span class="ot">&lt;-</span> <span class="fu">factor</span>(coffee_df<span class="sc">$</span>stir)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>coffee_df<span class="sc">$</span>block <span class="ot">&lt;-</span> <span class="fu">factor</span>(coffee_df<span class="sc">$</span>block)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coffee_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treatment material lid stir     block temp
1        T1  ceramic yes  yes   Morning  138
2        T1  ceramic yes  yes Afternoon  152
3        T2  ceramic yes   no   Morning  150
4        T2  ceramic yes   no Afternoon  150
5        T3  ceramic  no   no   Morning  126
6        T3  ceramic  no   no Afternoon  134</code></pre>
</div>
</div>
</section>
<section id="checking-for-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="checking-for-assumptions">Checking for Assumptions</h2>
<p>Before celebrating the results, we have to make sure the linear regression model isn’t lying to us. I ran standard diagnostics to check for normality, independence, and homoscedasticity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(temp <span class="sc">~</span> block <span class="sc">+</span> material <span class="sc">*</span> lid <span class="sc">*</span> stir, <span class="at">data =</span> coffee_df)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/diagnostics-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Looking at the plots, everything tracks cleanly along the diagonal lines and the residuals don’t funnel out, meaning our statistical assumptions hold up fine.</p>
</section>
<section id="the-results-breaking-down-the-anova" class="level2">
<h2 class="anchored" data-anchor-id="the-results-breaking-down-the-anova">The Results: Breaking Down the ANOVA</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>model_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(model_lm)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Df Sum Sq Mean Sq F value   Pr(&gt;F)    
block              1   63.4    63.4   4.871   0.0495 *  
material           2 2261.1  1130.5  86.889 1.82e-07 ***
lid                1  570.4   570.4  43.837 3.76e-05 ***
stir               1   26.0    26.0   2.001   0.1848    
material:lid       2  159.3    79.6   6.120   0.0163 *  
material:stir      2    3.1     1.5   0.118   0.8894    
lid:stir           1   18.4    18.4   1.412   0.2597    
material:lid:stir  2   32.2    16.1   1.239   0.3270    
Residuals         11  143.1    13.0                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>My Interpretation of the Data: - The Obvious Winners: material and lid have a <span class="math inline">\(p\)</span>-value way below <span class="math inline">\(0.001\)</span>. No surprise there. - The Interaction (material:lid): This is significant (<span class="math inline">\(p = 0.0163\)</span>). It mathematically proves that a lid’s effectiveness shifts drastically depending on the cup shape and material. - The Stirring Myth: Interestingly, stir was not significant (<span class="math inline">\(p = 0.1848\)</span>). For a short 10-minute window, the literal fluid motion of stirring barely impacted heat loss compared to the insulation properties of the cup.</p>
</section>
<section id="taking-a-closer-look-with-linear-contrasts" class="level2">
<h2 class="anchored" data-anchor-id="taking-a-closer-look-with-linear-contrasts">Taking a Closer Look with Linear Contrasts</h2>
<p>I wanted to compare physical properties only. ANOVA only tells me if at least one group mean differs but does not show where those difference exist. Hence, linear contrast in this case help to identify which factors are more significant when grouped in a certain way, like takeout cups vs reusable mugs etc.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'emmeans' was built under R version 4.4.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>material_emms <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(model_anova, <span class="st">"material"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Contrast 1: Insulated Metal vs. Non-Insulated (Ceramic &amp; Paper)</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Contrast 2: Takeout Paper vs. Permanent Reusable Mugs</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(material_emms, <span class="fu">list</span>(<span class="st">"Insulated Metal vs. Others"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.5</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="fl">0.5</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                   estimate   SE df t.ratio p.value
 Insulated Metal vs. Others     18.9 1.56 11  12.084 &lt;0.0001

Results are averaged over the levels of: block, lid, stir </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(material_emms, <span class="fu">list</span>(<span class="st">"Disposable Paper vs. Reusable"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">0.5</span>, <span class="dv">1</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                      estimate   SE df t.ratio p.value
 Disposable Paper vs. Reusable    -2.31 1.56 11  -1.481  0.1668

Results are averaged over the levels of: block, lid, stir </code></pre>
</div>
</div>
<p>The contrast shows that the insulated metal cup holds heat significantly better (by about 18.9°F) than everything else. However, the paper takeout cup and the reusable ceramic mug actually performed comparably over this 10-minute stretch (<span class="math inline">\(p = 0.1668\)</span>).</p>
</section>
<section id="interaction-plot" class="level2">
<h2 class="anchored" data-anchor-id="interaction-plot">Interaction Plot</h2>
<p>Honestly, at times interaction plot do show some insights, but in this experiment, it does not really show much sadly, things stayed relatively parallel and predictable.</p>
<p>While it would have been cool to see a massive 3-way interaction impact, discovering that factors like stirring operate independently of the cup material is a huge insight in itself. It proves the system is robust and predictable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Interaction plots</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(coffee_df<span class="sc">$</span>material, coffee_df<span class="sc">$</span>lid, coffee_df<span class="sc">$</span>temp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/interaction-plots-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(coffee_df<span class="sc">$</span>material, coffee_df<span class="sc">$</span>stir, coffee_df<span class="sc">$</span>temp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/interaction-plots-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(coffee_df<span class="sc">$</span>lid, coffee_df<span class="sc">$</span>stir, coffee_df<span class="sc">$</span>temp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/interaction-plots-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="using-tukeyhsd-to-visualise-the-difference" class="level2">
<h2 class="anchored" data-anchor-id="using-tukeyhsd-to-visualise-the-difference">Using TukeyHSD to visualise the difference</h2>
<p>So, we know from our main ANOVA table that <code>material</code> is heavily significant. But remember: ANOVA is a bit of a tease. It tells us, <em>“Hey, at least one of these cup materials performs differently than the others!”</em> But it doesn’t actually tell us <strong>which pairs</strong> are different.</p>
<p>Are ceramic and paper different? Are paper and metal different?</p>
<p>To find out, we could technically just run a bunch of individual <span class="math inline">\(t\)</span>-tests comparing every single combination. But there is a massive trap called <strong>Family Wise Error Rate [FWER] (The Multiplicity Problem)</strong>. Every time you run a statistical test, you have a 5% chance of claiming a false positive by pure luck. If you run dozens of tests, those 5% chances stack up fast, and your overall error rate skyrockets.</p>
<p>That is where <strong>Tukey’s Honest Significant Difference (TukeyHSD)</strong> steps in. It is “honest” because it adjusts our <span class="math inline">\(p\)</span>-values backward, keeping our global error rate strictly at 5%, no matter how many pairs we compare.</p>
<p>Let’s look at what happens when we run the full pairwise comparison across our cup materials:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(model_anova, <span class="st">"material"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = model_lm)

$material
                 diff        lwr       upr     p adj
metal-ceramic  23.625  18.753834 28.496166 0.0000001
paper-ceramic   9.500   4.628834 14.371166 0.0007107
paper-metal   -14.125 -18.996166 -9.253834 0.0000219</code></pre>
</div>
</div>
<hr>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<ol type="1">
<li>Primary Drivers of Heat Dispersal</li>
</ol>
<p>The experiment confirms that Cup Material and the use of a Lid are the most critical factors in maintaining coffee temperature (<span class="math inline">\(p &lt; 0.001\)</span>). The Ceramic cup was the superior performer for heat dispersal, losing significantly more heat than both the paper and metal alternatives. Post-hoc Tukey testing confirmed that all three materials are statistically distinct from one another, establishing a clear performance hierarchy: Ceramic &gt; Paper &gt; Metal.</p>
<ol start="2" type="1">
<li>The Interaction Effect (Material:Lid)</li>
</ol>
<p>A key finding of this study is the significant interaction between Material and Lid (<span class="math inline">\(p = 0.0163\)</span>). While the addition of a lid caused a deterioration of the heat dispersal effects across all groups, its impact was most dramatic for the Ceramic cup. This is likely due to the ceramic cup’s larger surface area relative to the paper and metal containers; the lid acts as a critical barrier against evaporation and convective heat loss that would otherwise be maximized in an open-top ceramic vessel.</p>
<ol start="3" type="1">
<li>Insights from Linear Contrasts</li>
</ol>
<p>Insulated vs.&nbsp;Non-Insulated: The contrast comparing the insulated metal cup against the average of the others was highly significant (<span class="math inline">\(p &lt; 0.0001\)</span>), with an estimate of 18.9°F. This underscores that specialized vacuum or double-wall insulation is far more effective in heat retention than standard material density.</p>
<p>The contrast between the paper (disposable) cup and the average of the reusable cups (ceramic and metal) was not significant (<span class="math inline">\(p = 0.1668\)</span>). This suggests that a standard paper takeout cup performs comparably to the average of “permanent” household mugs in short-duration (10-minute) heat dispersion.</p>
<ol start="4" type="1">
<li>Non-Significant Factors and Environmental Control</li>
</ol>
<p>The Stirring factor and its associated interactions were not significant (<span class="math inline">\(p = 0.1848\)</span>). This indicates that the internal movement of the liquid has a negligible effect on cooling compared to the external insulation and surface-level heat loss. Finally, the significance of the Blocking factor (<span class="math inline">\(p = 0.0495\)</span>) justifies the experimental design choice to account for time-of-day variations, ensuring that environmental shifts between morning and afternoon did not bias the treatment effects.</p>
<p>Final Recommendation: To achieve the optimal (fastest) cooling, the experiment suggests using a Ceramic cup without a lid. While the ‘Stirring’ factor did not reach statistical significance (<span class="math inline">\(p = 0.18\)</span>), the Material:Lid interaction (<span class="math inline">\(p = 0.016\)</span>) proves that the cooling effect of removing the lid is most potent when using a wide-mouthed ceramic vessel. Conversely, if the goal is to prevent cooling, an insulated metal cup with a lid should be used.</p>
<hr>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/yingghui23\.github\.io\/personal-blog\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>