project:
  type: website
  output-dir: docs

execute: 
  freeze: true

website:
  description: "A data analytics and statistics blog"
  site-url: https://yingghui23.github.io/personal-blog/
  favicon: logo.png
  navbar:
    background: "#2A3439"
    logo: logontitle.png
    type: dark
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yingghui23
      - icon: linkedin
        href: https://www.linkedin.com/in/tan-ying-hui23/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3ByB3dxP8gQESEyO24EnDJ%2BA%3D%3D
      
format:
  html:
    theme: darkly
    css: styles.css



