{
  "hash": "2f28c739b4e6105e3f8d313b2ec61414",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"A 3x2x2 Factorial Design on Coffee Cooling\"\ndescription: \"Using an Analysis of Variance (ANOVA) and linear contrasts in R to determine the optimal combination of cup material, lids, and stirring for heat dispersal.\"\nauthor: \"Ying Hui Tan\"\ndate: \"2026-06-01\"\ncategories: [DOE, R, BIBD]\nimage: coffee.jpg\n---\n\n## Overview: The Core Objective\n\nWhile it seems like common sense on which factors affect coffee cooling in general, I guess the main point of this blog is to understand the key concepts of Design of Experiment (DoE). Elements like linear contrast and factorial design could be applied to real world data in manufacturing plants or product analytics.  \n\n---\n\n## The Problem: What Cools Coffee Fastest?\n\nEver wondered what is the optimal way to cool down hot coffee? In this project, we experiment with different methods of cooling a cup of coffee by varying three factors: the material of the cup, stirring, and the addition of a lid. The goal is to determine the most effective combination for cooling coffee under controlled environmental conditions.\n\nThe primary response variable is the **temperature of the coffee after a fixed time interval (10 minutes)**.\n\n---\n\n## Experimental Setup & Controls\n\nTo ensure consistency and isolate the true treatment effects, several critical engineering controls were implemented:\n* **Fixed Environment:** All trials were conducted in a single room with the thermostat locked at **80°F**.\n* **Standardized Initial State:** Water was heated in the same vessel to a full boil, poured immediately, and standardized to an initial temperature of **180°F**.\n* **Standardized Stirring:** The stirring protocol was strictly controlled at **1 rotation per second for exactly 1 minute**.\n* **System Cleanliness:** Cups were thoroughly washed and allowed to rest for 15 minutes before reuse to return to room temperature.\n\n### Factors of Interest (3x2x2 Factorial Design)\nWe evaluated 12 distinct treatment combinations with **2 replications per treatment**, resulting in a total of 24 experimental units (individual cups of coffee).\n\n* **Cup Material (3 Levels):** Ceramic, Paper, Insulated Metal\n* **Lid (2 Levels):** Lid (+) vs. No Lid (-)\n* **Stirring (2 Levels):** Stir (+) vs. No Stir (-)\n\nIn addition to the factorial design, there is a blocking effect (Morning vs Afternoon), in consideration of the time frame the experiement is conducted. Hence, this is a 3x2x2 Full Factorial Design arranged in Randomised Complete Block Design (RCBD).\n\nThe statistical linear model for this 3x2x2 randomized blocked factorial design is expressed as:\n\n$$Y_{ijkl} = \\mu + \\gamma_i + \\alpha_j + \\beta_k + \\delta_l + (\\alpha\\beta)_{jk} + (\\alpha\\delta)_{jl} + (\\beta\\delta)_{kl} + (\\alpha\\beta\\delta)_{jkl} + \\epsilon_{ijkl}$$\n\nDefinition of Terms:\n* $Y_{ijkl}$: The observed final coffee temperature for the $i$-th block, $j$-th cup material, $k$-th lid status, and $l$-th stirring status.\n\n* $\\mu$: The overall grand mean of the coffee temperature.$\\gamma_i$: The effect of the $i$-th Block (Morning vs. Afternoon), where $i = 1, 2$.\n\n* $\\alpha_j$: The main effect of the $j$-th factor, Cup Material (Ceramic, Paper, Insulated Metal), where $j = 1, 2, 3$.\n\n* $\\beta_k$: The main effect of the $k$-th factor, Lid (Yes vs. No), where $k = 1, 2$.\n\n* $\\delta_l$: The main effect of the $l$-th factor, Stirring (Yes vs. No), where $l = 1, 2$.\n\n* $(\\alpha\\beta)_{jk}$: The 2-way interaction effect between Cup Material and Lid. (Significant in your data!)\n\n* $(\\alpha\\delta)_{jl}$: The 2-way interaction effect between Cup Material and Stirring.\n\n* $(\\beta\\delta)_{kl}$: The 2-way interaction effect between Lid and Stirring.\n\n* $(\\alpha\\beta\\delta)_{jkl}$: The 3-way interaction effect between Cup Material, Lid, and Stirring.\n\n* $\\epsilon_{ijkl}$: The random experimental error term, assumed to be independent and identically distributed (i.i.d.) following a normal distribution: $\\epsilon_{ijkl} \\sim N(0, \\sigma^2)$.\n\n---\n\n## Data Loading & The Raw Numbers\n\nTo analyze this properly, I loaded the 24 experimental runs into R. I also accounted for a **Blocking Factor** (Morning vs. Afternoon runs) just in case the ambient temperature outside leaked into the room and messed with our data. \n\nHere is what the raw dataset looks like:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating our 3x2x2 factorial dataset\ncoffee_df <- data.frame(\n  treatment = rep(paste0(\"T\", 1:12), each = 2),\n  material = rep(c(\"ceramic\",\"ceramic\",\"ceramic\",\"ceramic\",\n                   \"paper\",\"paper\",\"paper\",\"paper\",\n                   \"metal\",\"metal\",\"metal\",\"metal\"), each = 2),\n  lid = rep(c(\"yes\",\"yes\",\"no\",\"no\",\n              \"no\",\"no\",\"yes\",\"yes\",\n              \"yes\",\"yes\",\"no\",\"no\"), each = 2),\n  stir = rep(c(\"yes\",\"no\",\"no\",\"yes\",\n               \"no\",\"yes\",\"no\",\"yes\",\n               \"yes\",\"no\",\"no\",\"yes\"), each = 2),\n  block = rep(c(\"Morning\", \"Afternoon\"), times = 12),\n  temp = c(\n    138,152,150,150,126,134,126,136,146,150,144,143,\n    150,154,152,149,162,165,168,169,158,158,161,160\n  )\n)\n\n# Converting characters to factors for ANOVA\ncoffee_df$material <- factor(coffee_df$material)\ncoffee_df$lid <- factor(coffee_df$lid)\ncoffee_df$stir <- factor(coffee_df$stir)\ncoffee_df$block <- factor(coffee_df$block)\n\nhead(coffee_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  treatment material lid stir     block temp\n1        T1  ceramic yes  yes   Morning  138\n2        T1  ceramic yes  yes Afternoon  152\n3        T2  ceramic yes   no   Morning  150\n4        T2  ceramic yes   no Afternoon  150\n5        T3  ceramic  no   no   Morning  126\n6        T3  ceramic  no   no Afternoon  134\n```\n\n\n:::\n:::\n\n\n## Checking for Assumptions\n\nBefore celebrating the results, we have to make sure the linear regression model isn't lying to us. I ran standard diagnostics to check for normality, independence, and homoscedasticity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_lm <- lm(temp ~ block + material * lid * stir, data = coffee_df)\npar(mfrow = c(2, 2))\nplot(model_lm)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/diagnostics-1.png){width=768}\n:::\n:::\n\n\nLooking at the plots, everything tracks cleanly along the diagonal lines and the residuals don't funnel out, meaning our statistical assumptions hold up fine.\n\n## The Results: Breaking Down the ANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_anova <- aov(model_lm)\nsummary(model_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Df Sum Sq Mean Sq F value   Pr(>F)    \nblock              1   63.4    63.4   4.871   0.0495 *  \nmaterial           2 2261.1  1130.5  86.889 1.82e-07 ***\nlid                1  570.4   570.4  43.837 3.76e-05 ***\nstir               1   26.0    26.0   2.001   0.1848    \nmaterial:lid       2  159.3    79.6   6.120   0.0163 *  \nmaterial:stir      2    3.1     1.5   0.118   0.8894    \nlid:stir           1   18.4    18.4   1.412   0.2597    \nmaterial:lid:stir  2   32.2    16.1   1.239   0.3270    \nResiduals         11  143.1    13.0                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nMy Interpretation of the Data:\n- The Obvious Winners: material and lid have a $p$-value way below $0.001$. No surprise there.\n- The Interaction (material:lid): This is significant ($p = 0.0163$). It mathematically proves that a lid's effectiveness shifts drastically depending on the cup shape and material.\n- The Stirring Myth: Interestingly, stir was not significant ($p = 0.1848$). For a short 10-minute window, the literal fluid motion of stirring barely impacted heat loss compared to the insulation properties of the cup.\n\n## Taking a Closer Look with Linear Contrasts\n\nI wanted to compare physical properties only. ANOVA only tells me if at least one group mean differs but does not show where those difference exist. Hence, linear contrast in this case help to identify which factors are more significant when grouped in a certain way, like takeout cups vs reusable mugs etc.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'emmeans' was built under R version 4.4.3\n```\n\n\n:::\n\n```{.r .cell-code}\nmaterial_emms <- emmeans(model_anova, \"material\")\n\n# Contrast 1: Insulated Metal vs. Non-Insulated (Ceramic & Paper)\n# Contrast 2: Takeout Paper vs. Permanent Reusable Mugs\ncontrast(material_emms, list(\"Insulated Metal vs. Others\" = c(-0.5, 1, -0.5)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                   estimate   SE df t.ratio p.value\n Insulated Metal vs. Others     18.9 1.56 11  12.084 <0.0001\n\nResults are averaged over the levels of: block, lid, stir \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrast(material_emms, list(\"Disposable Paper vs. Reusable\" = c(-0.5, -0.5, 1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                      estimate   SE df t.ratio p.value\n Disposable Paper vs. Reusable    -2.31 1.56 11  -1.481  0.1668\n\nResults are averaged over the levels of: block, lid, stir \n```\n\n\n:::\n:::\n\n\nThe contrast shows that the insulated metal cup holds heat significantly better (by about 18.9°F) than everything else. However, the paper takeout cup and the reusable ceramic mug actually performed comparably over this 10-minute stretch ($p = 0.1668$).\n\n## Interaction Plot\n\nHonestly, at times interaction plot do show some insights, but in this experiment, it does not really show much sadly, things stayed relatively parallel and predictable. \n\nWhile it would have been cool to see a massive 3-way interaction impact, discovering that factors like stirring operate independently of the cup material is a huge insight in itself. It proves the system is robust and predictable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Interaction plots\ninteraction.plot(coffee_df$material, coffee_df$lid, coffee_df$temp)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/interaction-plots-1.png){width=672}\n:::\n\n```{.r .cell-code}\ninteraction.plot(coffee_df$material, coffee_df$stir, coffee_df$temp)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/interaction-plots-2.png){width=672}\n:::\n\n```{.r .cell-code}\ninteraction.plot(coffee_df$lid, coffee_df$stir, coffee_df$temp)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/interaction-plots-3.png){width=672}\n:::\n:::\n\n\n---\n\n## Using TukeyHSD to visualise the difference\n\nSo, we know from our main ANOVA table that `material` is heavily significant. But remember: ANOVA is a bit of a tease. It tells us, *\"Hey, at least one of these cup materials performs differently than the others!\"* But it doesn’t actually tell us **which pairs** are different. \n\nAre ceramic and paper different? Are paper and metal different? \n\nTo find out, we could technically just run a bunch of individual $t$-tests comparing every single combination. But there is a massive trap called **Family Wise Error Rate [FWER] (The Multiplicity Problem)**. Every time you run a statistical test, you have a 5% chance of claiming a false positive by pure luck. If you run dozens of tests, those 5% chances stack up fast, and your overall error rate skyrockets.\n\nThat is where **Tukey’s Honest Significant Difference (TukeyHSD)** steps in. It is \"honest\" because it adjusts our $p$-values backward, keeping our global error rate strictly at 5%, no matter how many pairs we compare.\n\nLet's look at what happens when we run the full pairwise comparison across our cup materials:\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(model_anova, \"material\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = model_lm)\n\n$material\n                 diff        lwr       upr     p adj\nmetal-ceramic  23.625  18.753834 28.496166 0.0000001\npaper-ceramic   9.500   4.628834 14.371166 0.0007107\npaper-metal   -14.125 -18.996166 -9.253834 0.0000219\n```\n\n\n:::\n:::\n\n\n---\n\n## Conclusion \n\n1. Primary Drivers of Heat Dispersal\n\nThe experiment confirms that Cup Material and the use of a Lid are the most critical factors in maintaining coffee temperature ($p < 0.001$). The Ceramic cup was the superior performer for heat dispersal, losing significantly more heat than both the paper and metal alternatives. Post-hoc Tukey testing confirmed that all three materials are statistically distinct from one another, establishing a clear performance hierarchy: Ceramic > Paper > Metal.\n\n2. The Interaction Effect (Material:Lid)\n\nA key finding of this study is the significant interaction between Material and Lid ($p = 0.0163$). While the addition of a lid caused a deterioration of the heat dispersal effects across all groups, its impact was most dramatic for the Ceramic cup. This is likely due to the ceramic cup’s larger surface area relative to the paper and metal containers; the lid acts as a critical barrier against evaporation and convective heat loss that would otherwise be maximized in an open-top ceramic vessel.\n\n3. Insights from Linear Contrasts\n\nInsulated vs. Non-Insulated: The contrast comparing the insulated metal cup against the average of the others was highly significant ($p < 0.0001$), with an estimate of 18.9°F. This underscores that specialized vacuum or double-wall insulation is far more effective in heat retention than standard material density.\n\nThe contrast between the paper (disposable) cup and the average of the reusable cups (ceramic and metal) was not significant ($p = 0.1668$). This suggests that a standard paper takeout cup performs comparably to the average of \"permanent\" household mugs in short-duration (10-minute) heat dispersion.\n\n4. Non-Significant Factors and Environmental Control\n\nThe Stirring factor and its associated interactions were not significant ($p = 0.1848$). This indicates that the internal movement of the liquid has a negligible effect on cooling compared to the external insulation and surface-level heat loss. Finally, the significance of the Blocking factor ($p = 0.0495$) justifies the experimental design choice to account for time-of-day variations, ensuring that environmental shifts between morning and afternoon did not bias the treatment effects.\n\nFinal Recommendation:\nTo achieve the optimal (fastest) cooling, the experiment suggests using a Ceramic cup without a lid. While the 'Stirring' factor did not reach statistical significance ($p = 0.18$), the Material:Lid interaction ($p = 0.016$) proves that the cooling effect of removing the lid is most potent when using a wide-mouthed ceramic vessel. Conversely, if the goal is to prevent cooling, an insulated metal cup with a lid should be used.\n\n---",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}